### ISSUE TITLE
Authentication for transactions extension's endpoints

### ISSUE THREAD

**Issue by pantierra** [stac-utils/stac-fastapi-pgstac#166]
The transaction extension enables manipulation of data within the STAC catalog. To enhance its utility, it would be beneficial to incorporate optional authentication for this endpoint. Are there any plans or preferred approaches for implementing this feature?

**Comment by vincentsarago** [comment]
@pantierra We usually suggest people to customize their own stac-fastapi application and add auth using route-dependencies 

there is a nice example in https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/tree/main/examples/auth

we could write something similar for this repo

**Comment by pantierra** [comment]
Nice! Would it be worthwhile to consider extending the [STAC API Authentication extension](https://github.com/stac-extensions/authentication)?

**Comment by pantierra** [comment]
Reporting back on this, indeed we probably want to have this in front of `stac-fastpi` and there are several possibilities:

* Incorporate [eoapi-auth-utils](https://github.com/developmentseed/eoapi-auth-utils) with `stac-fastpi` to solve this at a runtime level. In line of what @vincentsarago suggested above.
* Put a dedicated [stac-auth-proxy](https://github.com/developmentseed/stac-auth-proxy) in front of it.
* Resolve this on a reverse proxy or API Gateway level in a more complex infrastructure setup.

So let's close this here. Sorry for causing noise.
