### ISSUE TITLE
How to append change the baseurl from http to https?

### ISSUE THREAD

**Issue by mkmitchell** [stac-utils/stac-fastapi-pgstac#62]
I'm guessing this is pretty straight forward but I don't yet have a lot of experience with many of these technologies.  When I try to access my api endpoint with pystac and get collections it reports it couldn't read my uri because it's attempting to read http instead of https.

In my api/links I see that my root url is listed has http.  Can I easily change this?
I tried adding the env variable 'REQUEST_BASE_URL'='https:/rooturl' in docker-compose.yml but it didn't change anything.

**Comment by vincentsarago** [comment]
@mkmitchell This depends how you deployed your API!
ref: https://github.com/developmentseed/titiler/discussions/345, https://github.com/developmentseed/titiler/discussions/342

if you are using Uvicorn for the server it might just be a configuration issue

**Comment by mkmitchell** [comment]
I'll close this issue.  I rebuilt the image and it seemed to work fine.  I don't believe I changed anything.  Thanks for the help and links @vincentsarago
