### ISSUE TITLE
GRANT STAC API ACCESS TO SPECIFIC USER AND COLLECTION

### ISSUE THREAD

**Issue by NVTuann201** [stac-utils/stac-fastapi-pgstac#66]
Hi everyone. I'm having a problem that I could not find out how to grant permission for specific collection. 
Can anyone help me about this? Because I need to handle the traffic to my api server for specific user and collection.
Thanks so much!

**Comment by gadomski** [comment]
Are you talking about collection-level authentication? If so, that doesn't exist in **stac-fastapi** at this time. Folks have been rolling their own authentication solutions outside of this repo up to this point.
